name: Build Action with NCC

on:
  push:
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # We'll use PAT to commit

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build with ncc
        run: npx ncc build src/index.js -o dist

      - name: Commit and push dist/
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add dist
          git commit -m "Build: update dist folder [skip ci]" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
