name: Notify External Server on PR
on:
  pull_request:
    types: [opened]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR Details to External Server
        env:
          EXTERNAL_SERVER_URL: https://c1a3-103-214-61-236.ngrok-free.app/pr
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          REPO_FULL_NAME: ${{ github.repository }}
        run: |
          curl -X POST $EXTERNAL_SERVER_URL \
          -H "Content-Type: application/json" \
          -d '{
            "pr_number": "'$PR_NUMBER'",
            "pr_title": "'$PR_TITLE'",
            "pr_author": "'$PR_AUTHOR'",
            "pr_url": "'$PR_URL'",
            "repo_full_name": "'$REPO_FULL_NAME'"
          }'
